version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "/cli/spring-boot"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "/examples/quarkus-cli"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "/examples/spring-boot-cli"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
