= Plain Java native

Experimental repo to assess complexity of building a native image only using 'org.graalvm.buildtools.native'.
'base' module is a simple "HelloWorld" project for comparison (see `ci/stats.sh`).

// diary https://twitter.com/abelsromero/status/1675556510976335872

== Setup

. Install Graal (using Liberica NIK to simplify steps)

 sdk i java 23.0.2-graalce

. Create Gradle project

 gradle init

. Add plugin and settings repo https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#_adding_the_plugin

. Compile

 ./gradlew :app:nativeCompile

. Run 🚀

 ./app/build/native/nativeCompile/app

NOTE: 'app' module also includes 'application' to generate runnable distributions, but that's not required for the native build.

== Testing

One failing and one successful test are included to validate https://junit.org/junit5/[Junit 5] and https://assertj.github.io/doc/[AssertJ].

To run tests in JVM:

 ./gradlew :app:test

To only run tests in native image (ignore `test` or else the native test compile does not run):

 ./gradlew nativeTest -x test

The later will generate a binary with the tests embedded in _./app/build/native/nativeTestCompile/my-app-tests_

== known issue

* Mockito is not supported for native test compilation.
https://github.com/oracle/graalvm-reachability-metadata/pull/141

* JCommander requires several classes to be added for reflection (`reflect-config.json`).
The Graal Agent can be run with `./gradlew -Pagent :java-modules:cli-args-jcommander:nativeTest`.

[TIP]
====
In case of errors locating 'native-image-agent'.
For example:
----
Could not find agent library native-image-agent on the library path, with error: libnative-image-agent.so: cannot open shared object file: No such file or directory
----

Set `LD_LIBRARY_PATH` to the proper path.
If you use SDKMAN! and Graal is set as current, "LD_LIBRARY_PATH=$JAVA_HOME/lib"`.
====

* As of date 5/10/23 logback-classic up v1.4.8 works.
v1.4.9 has https://github.com/oracle/graalvm-reachability-metadata/blob/master/metadata/ch.qos.logback/logback-classic/1.4.9/[metadata] but it does not work (binary is small and logs don't show).
